### ISSUE TITLE
Moves won't roll when the 'Cinder and Wraith' box is ticked in Configure Settings

### ISSUE THREAD

**Issue by Angrymog** [ben/foundry-ironsworn#1034]
As per the subject.  When this box is ticked, Moves don't roll, nor will stats.

**Comment by ben** [comment]
I spent some time tracking this down, and it turns out the cinder-wraith checkbox doesn't matter, they don't roll in any case. And the culprit is that something inside dice-so-nice changed. Make sure this checkbox is unticked and it'll work again:

![CleanShot 2024-10-30 at 17 03 58](https://github.com/user-attachments/assets/84849a92-feb5-466a-a363-813ac616fcb3)

Something to do with whether this actor is "owned" by the person triggering the roll, which in this game it probably isn't.

**Comment by Angrymog** [comment]
This is really wierd, because I didn't have Dice so Nice enabled.  When I enabled it, and made sure that the ticky box was unticked, both this issue and my Uncursed Oracles not rolling didn't occur.

**Comment by Angrymog** [comment]
Done a bit more testing - that ticky box doesn't change anything for me - it's all down to whether DSN is enabled or not.

DSN enabled - everything works
DSN non enabled - Uncursed oracles don't work and Wraith+Cinder tickybox stops normal rolls from working.

With DSN enabled and the Cinder and Wraith box ticked, the dice in the chat log are labelled, and the 3d dice have different colours, but the chatlog dice are just grey.

**Comment by Angrymog** [comment]
My DSN wasn't up to date; updated it and I can re-create your actions with the tickybox now.

**Comment by ben** [comment]
Fixed in release 1.24.5, thanks!
