### ISSUE TITLE
suggestion: change default action on title click on moves without action rolls

### ISSUE THREAD

**Issue by rsek** [ben/foundry-ironsworn#372]
currently, clicking on the title of a move without an action roll sends the entire text of the move to chat.

<img width="341" alt="Screen Shot 2022-05-20 at 5 28 46 PM" src="https://user-images.githubusercontent.com/5354757/169627019-9b87f619-0019-4871-a622-4cd6a0e7776a.png">
<img width="332" alt="Screen Shot 2022-05-20 at 5 30 25 PM" src="https://user-images.githubusercontent.com/5354757/169627077-aaf454a8-fb61-4409-98f5-7faaee28e0af.png">

since this is the "primary" action of the largest click target, it's easy to accidentally send a long move text to chat... and my gut feeling is that sending a move's full text to chat is much less commonly needed than just expanding the accordion section to look at it.

so, it might make sense to have it expand the accordion section containing the move's full text instead. this might mean revising some of the list controls to maintain internal consistency, though. personally, i don't think there's many situations where i'd want to clutter chat without looking at the text i was sending first... so maybe the "Send the whole text to chat" function is something to put *inside* the accordion (in other words, you open it to see the text and there's a button included to send it to chat, with an icon like 💬). that'd make it possible to send the text of moves with action rolls as well.

but maybe it'd be better if it stayed out of the chatlog altogether: a more advanced solution might look a little like the GM function "show picture to players, but for move text - a dismissable popup modal.

**Comment by ben** [comment]
The biggest reason it behaves the way it does now is because I saw people playing through [entire sessions](https://www.youtube.com/watch?v=vah1uSCGZU0) not knowing that the "cube" icon was clickable, and that it would provide context before and after the roll. The current design assumes that "do the roll" is the primary action for each move, and an inline preview is provided via the 👁️.

Here's a rough concept:

![CleanShot 2022-05-30 at 08 00 23](https://user-images.githubusercontent.com/39902/171018821-45d362b8-5721-4782-8f56-aab5fd5cfe9b.jpg)

The title text would expand the accordion, and we add buttons for both possible actions inside. The d10 in the title row would act as a shortcut to the "do the roll" action, and we echo the d10 icon inside to suggest that icon as a synonym. This would probably strike the right balance of not-surprise and power, so I'll go ahead and do that.

None of this addresses your background concern, which is what happens when the user clicks "do the roll" for moves like _Begin a Session_. We could:

* Do the Foundry-normal thing, and pump the item's description to the chat log (current behavior)
* Remove the d10 buttons for these moves, but that makes the display look patchy, like there's a bug
* Gray out the d10 buttons for these moves, but now we have to explain _why_ they're grayed out
* Pop up a journal-style window, which is new behavior that doesn't happen anywhere else in this or any system

I've thought about this a lot, and there's no perfect answer. Maybe graying them out is the answer, but that patchy look isn't great.

![CleanShot 2022-05-30 at 08 09 08](https://user-images.githubusercontent.com/39902/171020424-dd196aba-0254-485e-a48c-14317a2b766c.jpg)
![CleanShot 2022-05-30 at 08 10 32](https://user-images.githubusercontent.com/39902/171020544-5d2e5368-bf04-492a-9f06-1561e7cd0e99.jpg)

**Comment by ben** [comment]
Settling on the solution merged with #379, so I'll close this for now.
