### ISSUE TITLE
Truths text is fetched from sf-setting-truths.json instead of en.json

### ISSUE THREAD

**Issue by phenomen** [ben/foundry-ironsworn#395]
Here is an example (see Cataclysm header):
![image](https://user-images.githubusercontent.com/138311/174943477-da844607-fb29-4151-a06e-43d34e35456b.png)

**Comment by ben** [comment]
Yeah, this is a holdover from the initial development cycles, and I haven't changed it because fetching from `en.json` isn't the way we want to go with this going forward. The place we want to be looks like this:

- All "book" content (i.e. moves, oracles, truths) exist as compendium items, and should be translated via [Babele](https://gitlab.com/riccisi/foundryvtt-babele#foundryvtt-babele).
- Whatever's left for the UI (i.e. "Burn momentum", "Iron", "Wounded") is translated using `en.json` and friends.

Currently, Ironsworn does very little of that — all content is still fetched from `en.json` — and Starforged does most of it, since _most_ content is in compendia. You found the slice of book content that's still in the old system, and that's because I haven't gotten around to moving it into a journal compendium yet.

**Comment by phenomen** [comment]
Babele approach sounds good to me since we use it for 5e, PF2, SWADE, Alien, Corilois and other systems.
