### ISSUE TITLE
Error when starting with v1.22.0

### ISSUE THREAD

**Issue by derSebastian** [ben/foundry-ironsworn#865]
When launching the world I encountered several errors during start that canceled the world launch.

Each called meterfield.ts before:

Migrating sourceData, fieldData Object
biography: ""debility: {corrupted: false, cursed: false, encumbered: false, maimed: false, shaken: false, …}edge: 2health: {value: 5, max: 5, min: 0}heart: 1iron: 3legacies: {quests: 0, questsXpSpent: 0, bonds: 0, bondsXpSpent: 0, discoveries: 0, …}momentum: {value: 2, max: 10, min: -6, resetValue: 2}notes: ""shadow: 2spirit: {value: 5, max: 5, min: 0}supply: {value: 5, max: 5, min: 0}wits: 1xp: 0[[Prototype]]: Object 2

TypeError: Failed data migration for CharacterModel: Cannot create property 'resetValue' on number '2'

After the third time it did start. Going back to my notes it seems that the Health, Spirit, and Supply were reset to their original values not the ones I had noted during the end of the session. My momentum was at reset already.

**Comment by rsek** [comment]
hm, i think i know what's happening here. `sourceData` appears to refer to the entire actor source data object, but i assumed it referred to the source data of the field's direct parent, e.g. `actor.system`. that means some dot paths i use for migrations are pointing to nothing, so certain momentum-related migrations aren't firing properly.

though, i'm not sure we need to have migrations for `resetValue` in the first place, now that i look at it. it's effectively a computed property and we don't really expose it to the user. (it exists on my AE branch, mainly because AEs want the properties they modify to exist in the actor source data).

**Comment by rsek** [comment]
simple way to repro:
drop `Actor.create({name: 'Migration Test', type: 'character',system: {momentum: 5, edge: 3, health: 2}})` into the browser console, then open the character sheet for the new actor. observe that `momentum` and `health` fallback to default values, but `edge` is fine.

this appears only to affect characters that need their meters migrated from plain numeric value to the new data model. something is inserting the fallback value before our code has a chance to cast the `number` to a meter-shaped object.

thus, if you create a character with `Actor.create({name: 'Non-Migration Test', type: 'character',system: {momentum: {value:5}, edge: 3, health: {value:2}}})`, things work normally.
